export const RETRIEVE_SPOTIFY_PLAYLIST = 'RETRIEVE_SPOTIFY_PLAYLIST';
export const RECEIVE_SPOTIFY_PLAYLIST_FAIL = 'RECEIVE_SPOTIFY_PLAYLIST_FAIL';
export const RECEIVE_SPOTIFY_PLAYLIST_SUCCESS = 'RECEIVE_SPOTIFY_PLAYLIST_SUCCESS';


export const RETRIEVE_SPOTIFY_PLAYLISTS = 'RETRIEVE_SPOTIFY_PLAYLISTS';
export const RECEIVE_SPOTIFY_PLAYLISTS_FAIL = 'RECEIVE_SPOTIFY_PLAYLISTS_FAIL';
export const RECEIVE_SPOTIFY_PLAYLISTS_SUCCESS = 'RECEIVE_SPOTIFY_PLAYLISTS_SUCCESS';

export const RETRIEVE_YOUTUBE_VIDEOS = 'RETRIEVE_YOUTUBE_PLAYLISTS';
export const RECEIVE_YOUTUBE_VIDEOS_FAIL = 'RECEIVE_YOUTUBE_PLAYLISTS_FAIL';
export const RECEIVE_YOUTUBE_VIDEOS_SUCCESS = 'RECEIVE_YOUTUBE_PLAYLISTS_SUCCESS';

export const RETRIEVE_KEYS = 'RETRIEVE_KEYS';
export const GET_KEYS_SUCCESS = 'GET_KEYS_SUCCESS';
export const GET_KEYS_FAIL = 'GET_KEYS_FAIL';